set(MPI_PATH "/home/yuansun/software/gcc/mpich/4.0.2")
set(HDF5_PATH "/home/yuansun/software/gcc/hdf5/1.12.3")
set(NETCDF_C_PATH "/home/yuansun/software/gcc/netcdf-c/4.9.2")
set(NETCDF_FORTRAN_PATH "/home/yuansun/software/gcc/netcdf-fortran/4.6.1")
set(PNETCDF_PATH "/home/yuansun/software/gcc/pnetcdf/1.12.3")
set(ESMF_LIBDIR "/home/yuansun/software/gcc/esmf/8.8.1/lib")
set(PIO_LIBDIR "/home/yuansun/software/gcc/pio/2.6.6/lib")
string(APPEND SLIBS " -L/home/yuansun/software/gcc/mpich/4.0.2/lib -lpnetcdf -Wl,-rpath,/home/yuansun/software/gcc/mpich/4.0.2/lib ")
string(APPEND SLIBS " -L/home/yuansun/software/gcc/hdf5/1.12.3/lib -lhdf5_fortran -lhdf5 -lhdf5_hl -lhdf5hl_fortran -Wl,-rpath,/home/yuansun/software/gcc/hdf5/1.12.3/lib")
string(APPEND SLIBS " -L/home/yuansun/software/gcc/pnetcdf/1.12.3/lib -lpnetcdf -Wl,-rpath,/home/yuansun/software/gcc/pnetcdf/1.12.3/lib")
string(APPEND SLIBS " -L/home/yuansun/software/gcc/netcdf-c/4.9.2/lib -lnetcdf -Wl,-rpath,/home/yuansun/software/gcc/netcdf-c/4.9.2/lib")
string(APPEND SLIBS " -L/home/yuansun/software/gcc/netcdf-fortran/4.6.1/lib -lnetcdff -Wl,-rpath,/home/yuansun/software/gcc/netcdf-fortran/4.6.1/lib")
string(APPEND SLIBS " -L/home/yuansun/software/gcc/esmf/8.8.1/lib -Wl,-rpath,/home/yuansun/software/gcc/esmf/8.8.1/lib")
string(APPEND SLIBS " -L/home/yuansun/software/gcc/pio/2.6.6/lib -Wl,-rpath,/home/yuansun/software/gcc/pio/2.6.6/lib")
string(APPEND SLIBS " -L/home/yuansun/software/gcc/lapack/3.9.0/ -llapack -lblas")
